### ISSUE TITLE
Readme - the link seems is broken

### ISSUE THREAD

**Issue by vitaly-pavluk** [chaoyangnz/simpledb#1]
Link on [http://www.cs.bc.edu/~sciore/simpledb/intro.html](http://www.cs.bc.edu/~sciore/simpledb/intro.html) is no longer available.
The response page is the default Apache server error 
```
Not Found
The requested URL /~sciore/simpledb/intro.html was not found on this server.

Apache/2.2.15 (Red Hat) Server at www.cs.bc.edu Port 443
```

**Comment by chaoyangnz** [comment]
Updated
